FROM node:20-alpine

WORKDIR /app

COPY Extractor_Spice_React/package*.json ./Extractor_Spice_React/
RUN cd Extractor_Spice_React && npm install

COPY Extractor_Spice_React ./Extractor_Spice_React
WORKDIR /app/Extractor_Spice_React

EXPOSE 5173

CMD ["npm", "run", "preview", "--", "--host"]
